export const GET_EVENTS = 'GET_EVENTS';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAIL = 'GET_EVENTS_FAIL';

export const RESET_EVENTS_CODE = 'RESET_EVENTS_CODE';
export const SET_FAVOURITE_EVENTS = 'SET_FAVOURITE_EVENTS';
